clusterGroup:
  namespaces:
    web-terminal: 
  projects:
    web-terminal:
  subscriptions: {}
  applications:
    web-terminal:
      name: web-terminal
      namespace: web-terminal
      project: web-terminal
      kustomize: true
      repoURL: https://github.com/redhat-cop/gitops-catalog.git
      path: web-terminal/aggregate/overlays/default
