{{- if .Values.global.certificates }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: custom-ca-openshift-gitops-policy
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: custom-ca-openshift-gitops
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: argocd-tls-certs-cm
                  namespace: openshift-gitops
                data:
                  {{- range .Values.global.certificates }}
                    {{ .fqdn }}: |
                      {{.certificate | quote}}
                  {{- end }}
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: argocd-tls-certs-cm
                  namespace:  {{ $.Values.global.pattern }}-{{ $.Values.main.clusterGroupName }}
                data:
                  {{- range .Values.global.certificates }}
                    {{ .fqdn }}: |
                      {{ .certificate | quote }}
                  {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: custom-ca-openshift-gitops-placement-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
placementRef:
  name: custom-ca-openshift-gitops-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: custom-ca-openshift-gitops-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: custom-ca-openshift-gitops-placement
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
      - key: local-cluster
        operator: NotIn
        values:
          - 'true'
{{- end }}
