# We copy the vp-private-repo-credentials from the "openshift-gitops" namespace
# to the "open-cluster-management" via the "private-hub-policy"
#
# Then we copy the secret from the "open-cluster-management" namespace to the
# managed clusters "openshift-gitops" instance
#
# And we also copy the same secret to the namespaced argo's namespace
{{- if and $.Values.global.certificates $.Values.clusterGroup.isHubCluster }}
{{- range $.Values.clusterGroup.managedClusterGroups }}
{{- $group := . }}
{{- if not .hostedArgoSites }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: custom-ca-{{ .name }}-gitops-policy
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: custom-ca-{{ .name }}-openshift-gitops
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: argocd-tls-certs-cm
                  namespace: openshift-gitops
                  labels:
                    app.kubernetes.io/managed-by: openshift-gitops-server
                    app.kubernetes.io/name: argocd-tls-certs-cm
                    app.kubernetes.io/part-of: argocd
                data:
                {{- range $.Values.global.certificates }}
                  {{ .fqdn }}: {{ .certificate | toYaml | indent 18 }}
                {{- end }}
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: argocd-tls-certs-cm
                  namespace:  {{ $.Values.global.pattern }}-{{ .name }}
                  labels:
                    app.kubernetes.io/managed-by: {{ .name }}-gitops-server
                    app.kubernetes.io/name: argocd-tls-certs-cm
                    app.kubernetes.io/part-of: argocd
                data:
                {{- range $.Values.global.certificates }}
                  {{ .fqdn }}: {{ .certificate | toYaml | indent 18 }}
                {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: custom-ca-{{ .name }}-placement-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
placementRef:
  name: custom-ca-{{ .name }}-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: custom-ca-{{ .name }}-gitops-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: custom-ca-{{ .name }}-placement
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
      - key: local-cluster
        operator: NotIn
        values:
          - 'true'
{{- end }}
{{- end }}
{{- end }}
