---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  extraValueFiles:
    - /overrides/values-common.yaml
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: false
  experimentalCapabilities: initcontainers
