---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  extraValueFiles: 
    - 'overrides/values-common-capabilities.yaml'
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
  experimentalCapabilities: initcontainers
