{{- if not (eq .Values.enabled "plumbing") }}
{{- $ns := .Values.clusterGroup.namespaces }}
{{- if kindIs "map" $ns }}
{{- range $k, $v := $ns }}{{- /* We loop here even though the map has always just one key */}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $k }}
  {{- if ne $v nil }}
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.global.pattern }}-{{ $.Values.clusterGroup.name }}
    {{- if $v.labels }}
    {{- range $key, $value := $v.labels }} {{- /* We loop here even though the map has always just one key */}}
    {{ $key }}: {{ $value | default "" | quote }}
    {{- end }}
    {{- end }}
  {{- if $v.annotations }}
  annotations:
    {{- range $key, $value := $v.annotations }} {{- /* We loop through the map to get key/value pairs */}}
    {{ $key }}: {{ $value | default "" | quote }}
    {{- end }}
  {{- end }}{{- /* if $v.annotations */}}
  {{- end }}
spec:
---
{{- end }}{{- /* range $k, $v := $ns */}}
{{- else }} {{- /* if kindIs "map" $ns */}}
{{- template "clustergroup.template.core.namespaces.list" (list .Values.clusterGroup.namespaces $.Values.global.pattern $.Values.clusterGroup.name) }}
{{- end }}{{- /* range $ns */}}
{{- end }}{{- /* if plumbing */}}
