compliance_operator:
  name: cluster
  namespace: openshift-compliance
  content: ssg-rhcos4-ds.xml
  profile: xccdf_org.ssgproject.content_profile_moderate
  storageClassName: crc-csi-hostpath-provisioner
  rotation: 10
  size: 10Gi 

